"""
MongoDB Document: Proposal

Development proposal generated by AI for ward councillors.
Collection: proposals
"""
from beanie import Document
from pydantic import Field
from typing import Optional, Dict, Any
from datetime import datetime


class ProposalMongo(Document):
    """
    AI-generated development proposal for a ward zone.
    Collection: proposals
    """
    proposal_id: str                              # short uuid hex
    ward_id: Optional[int] = None
    ward_name: Optional[str] = None
    councillor_name: Optional[str] = None
    development_type: str
    zone_lat: float
    zone_lng: float
    zone_cell_id: Optional[str] = None
    estimated_cost: Optional[float] = None
    total_complaints_evidence: int = 0
    ai_proposal_json: Dict[str, Any] = Field(default_factory=dict)
    docx_path: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = "draft"                        # draft | submitted | approved

    class Settings:
        name = "proposals"

    class Config:
        populate_by_name = True
