"""
MongoDB Document: WardCommunication

Stores AI-generated ward communications (formal notice, WhatsApp, SMS)
in English and Tamil generated by councillors.
Collection: ward_communications
"""
import uuid
from datetime import datetime
from typing import Optional, Dict, Any, Literal
from beanie import Document, Indexed
from pydantic import BaseModel, Field


class CommInput(BaseModel):
    topic_type: Literal[
        "work_completed", "upcoming_disruption",
        "scheme_announcement", "ward_event", "general_update"
    ]
    topic_summary: str
    specific_details: Optional[str] = None
    linked_ticket_id: Optional[str] = None
    linked_ticket_data: Optional[Dict[str, Any]] = None


class BilingualText(BaseModel):
    english: str = ""
    tamil: str = ""


class CommOutputs(BaseModel):
    formal_notice: BilingualText = Field(default_factory=BilingualText)
    whatsapp_post: BilingualText = Field(default_factory=BilingualText)
    sms: BilingualText = Field(default_factory=BilingualText)


class WardCommunicationMongo(Document):
    comm_id: Indexed(str, unique=True) = Field(  # type: ignore[valid-type]
        default_factory=lambda: uuid.uuid4().hex[:10]
    )
    ward_id: Indexed(str)  # type: ignore[valid-type]
    councillor_id: str
    councillor_name: str
    ward_name: str

    input: CommInput
    outputs: CommOutputs = Field(default_factory=CommOutputs)
    topic_label: str = ""

    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "ward_communications"
        indexes = [
            "ward_id",
            "councillor_id",
            "created_at",
        ]

    class Config:
        populate_by_name = True
