export const DEPT_NAMES: Record<string, string> = {
    D01: "Roads & Bridges",
    D02: "Buildings & Planning",
    D03: "Water Supply",
    D04: "Sewage & Drainage",
    D05: "Solid Waste Management",
    D06: "Street Lighting",
    D07: "Parks & Greenery",
    D08: "Health & Sanitation",
    D09: "Fire & Emergency",
    D10: "Traffic & Transport",
    D11: "Revenue & Property",
    D12: "Social Welfare",
    D13: "Education",
    D14: "Disaster Management",
};

export const PRIORITY_COLORS: Record<string, string> = {
    CRITICAL: "#DC2626",
    HIGH: "#EA580C",
    MEDIUM: "#CA8A04",
    LOW: "#16A34A",
};

export const PRIORITY_EMOJI: Record<string, string> = {
    CRITICAL: "🔴",
    HIGH: "🟠",
    MEDIUM: "🟡",
    LOW: "🟢",
};

export const STATUS_LABELS: Record<string, string> = {
    OPEN: "Open",
    ASSIGNED: "Assigned",
    IN_PROGRESS: "In Progress",
    PENDING_VERIFICATION: "Pending Verification",
    CLOSED: "Closed",
    CLOSED_UNVERIFIED: "Closed (Unverified)",
    REOPENED: "Reopened",
    REJECTED: "Rejected",
};

export const USER_ROLES: Record<string, string> = {
    SUPER_ADMIN: "Administrator",
    SUPERVISOR: "Ward Supervisor",
    JUNIOR_ENGINEER: "Junior Engineer",
    FIELD_STAFF: "Field Staff",
    COUNCILLOR: "Ward Councillor",
    PUBLIC_USER: "Citizen",
};

export const GRADE_COLORS: Record<string, string> = {
    EXCELLENT: "text-green-700 bg-green-100",
    GOOD: "text-blue-700 bg-blue-100",
    SATISFACTORY: "text-yellow-700 bg-yellow-100",
    NEEDS_IMPROVEMENT: "text-orange-700 bg-orange-100",
    POOR: "text-red-700 bg-red-100",
};

export const CHENNAI_CENTER: [number, number] = [13.0827, 80.2707];

export const WARD_NAMES: Record<number, string> = {
    1: "Kathivakkam",
    2: "Ennore",
    3: "Ernavoor",
    4: "Ajax",
    5: "Tiruvottiyur",
    6: "Kaladipet",
    7: "Rajakadai",
    8: "Kodungaiyur (West)",
    9: "Kodungaiyur (East)",
    15: "Edyanchavadi",
    18: "Manali",
    19: "Mathur",
    23: "Puzhal",
    26: "Madhavaram",
    34: "Tondiarpet",
    35: "New Washermenpet",
    36: "Old Washermenpet",
    38: "Perambur",
    39: "Vyasarpadi",
    43: "George Town",
    44: "Broadway",
    47: "Sowcarpet",
    56: "Ayanavaram",
    58: "Purasavakkam",
    60: "Royapuram",
    61: "Anna Salai",
    62: "Chepauk",
    64: "Kolathur",
    67: "Villivakkam",
    73: "Thiru-Vi-Ka-Nagar",
    75: "Otteri",
    79: "Kilpauk",
    88: "Ambattur",
    97: "Korattur",
    106: "Anna Nagar West",
    111: "Aminjikarai",
    114: "Chetpet",
    115: "Egmore",
    118: "Choolaimedu",
    127: "Choolaimedu",
    128: "Chepauk",
    129: "Nungambakkam",
    131: "Gopalapuram",
    132: "Royapettah",
    134: "Kodambakkam",
    135: "Triplicane",
    136: "T. Nagar",
    137: "Mylapore",
    139: "Alwarpet",
    140: "Nandanam",
    141: "R.A. Puram",
    144: "West Mambalam",
    145: "Koyambedu",
    146: "Virugambakkam",
    150: "Vadapalani",
    151: "K.K. Nagar",
    152: "Ashok Nagar",
    156: "Mugdha Nagar",
    160: "Alandur",
    165: "Adambakkam",
    170: "Kotturpuram",
    173: "Adyar",
    175: "Adyar",
    176: "Besant Nagar",
    178: "Thiruvanmiyur",
    179: "Velachery",
    181: "Perungudi",
    192: "Sholinganallur",
    195: "Ullagaram",
    198: "Madipakkam",
};

export const getWardLabel = (id: number) => {
    return WARD_NAMES[id] ? `${id} - ${WARD_NAMES[id]}` : `Ward ${id}`;
};
