export const DEPT_NAMES: Record<string, string> = {
    D01: "Roads & Bridges",
    D02: "Buildings & Planning",
    D03: "Water Supply",
    D04: "Sewage & Drainage",
    D05: "Solid Waste Management",
    D06: "Street Lighting",
    D07: "Parks & Greenery",
    D08: "Health & Sanitation",
    D09: "Fire & Emergency",
    D10: "Traffic & Transport",
    D11: "Revenue & Property",
    D12: "Social Welfare",
    D13: "Education",
    D14: "Disaster Management",
};

export const PRIORITY_COLORS: Record<string, string> = {
    CRITICAL: "#DC2626",
    HIGH: "#EA580C",
    MEDIUM: "#CA8A04",
    LOW: "#16A34A",
};

export const PRIORITY_EMOJI: Record<string, string> = {
    CRITICAL: "🔴",
    HIGH: "🟠",
    MEDIUM: "🟡",
    LOW: "🟢",
};

export const STATUS_LABELS: Record<string, string> = {
    OPEN: "Open",
    ASSIGNED: "Assigned",
    IN_PROGRESS: "In Progress",
    PENDING_VERIFICATION: "Pending Verification",
    CLOSED: "Closed",
    CLOSED_UNVERIFIED: "Closed (Unverified)",
    REOPENED: "Reopened",
    REJECTED: "Rejected",
    WITHDRAWN: "Withdrawn by Citizen",
};

export const USER_ROLES: Record<string, string> = {
    SUPER_ADMIN: "Administrator",
    SUPERVISOR: "Ward Supervisor",
    JUNIOR_ENGINEER: "Junior Engineer",
    FIELD_STAFF: "Field Staff",
    COUNCILLOR: "Ward Councillor",
    PUBLIC_USER: "Citizen",
};

export const GRADE_COLORS: Record<string, string> = {
    EXCELLENT: "text-green-700 bg-green-100",
    GOOD: "text-blue-700 bg-blue-100",
    SATISFACTORY: "text-yellow-700 bg-yellow-100",
    NEEDS_IMPROVEMENT: "text-orange-700 bg-orange-100",
    POOR: "text-red-700 bg-red-100",
};

export const CHENNAI_CENTER: [number, number] = [13.0827, 80.2707];
export const PRAYAGRAJ_CENTER: [number, number] = [25.4358, 81.8463];

export const WARD_NAMES: Record<number, string> = {
    1: "Kathivakkam",
    2: "Ennore",
    3: "Ernavoor",
    4: "Ajax",
    5: "Tiruvottiyur",
    6: "Kaladipet",
    7: "Rajakadai",
    8: "Kodungaiyur (West)",
    9: "Kodungaiyur (East)",
    15: "Edyanchavadi",
    18: "Manali",
    19: "Mathur",
    23: "Puzhal",
    26: "Madhavaram",
    34: "Tondiarpet",
    35: "New Washermenpet",
    36: "Old Washermenpet",
    38: "Perambur",
    39: "Vyasarpadi",
    43: "George Town",
    44: "Broadway",
    47: "Sowcarpet",
    56: "Ayanavaram",
    58: "Purasavakkam",
    60: "Royapuram",
    61: "Anna Salai",
    62: "Chepauk",
    64: "Kolathur",
    67: "Villivakkam",
    73: "Thiru-Vi-Ka-Nagar",
    75: "Otteri",
    79: "Kilpauk",
    88: "Ambattur",
    97: "Korattur",
    106: "Anna Nagar West",
    111: "Aminjikarai",
    114: "Chetpet",
    115: "Egmore",
    118: "Choolaimedu",
    127: "Choolaimedu",
    128: "Chepauk",
    129: "Nungambakkam",
    131: "Gopalapuram",
    132: "Royapettah",
    134: "Kodambakkam",
    135: "Triplicane",
    136: "T. Nagar",
    137: "Mylapore",
    139: "Alwarpet",
    140: "Nandanam",
    141: "R.A. Puram",
    144: "West Mambalam",
    145: "Koyambedu",
    146: "Virugambakkam",
    150: "Vadapalani",
    151: "K.K. Nagar",
    152: "Ashok Nagar",
    156: "Mugdha Nagar",
    160: "Alandur",
    165: "Adambakkam",
    170: "Kotturpuram",
    173: "Adyar",
    175: "Adyar",
    176: "Besant Nagar",
    178: "Thiruvanmiyur",
    179: "Velachery",
    181: "Perungudi",
    192: "Sholinganallur",
    195: "Ullagaram",
    198: "Madipakkam",
        1001: "Mahewa (Prayagraj)",
    1002: "Sulem Sarai (Prayagraj)",
    1003: "Bamhrouli Uparhar (Prayagraj)",
    1004: "Nibi Taluka Khurd (Prayagraj)",
    1005: "Pipalgaon (Prayagraj)",
    1006: "Kanihar (Prayagraj)",
    1007: "Rajapur (Prayagraj)",
    1008: "Tenduavan (Prayagraj)",
    1009: "Sonauti (Prayagraj)",
    1010: "Gohri (Prayagraj)",
    1011: "Amarsapur (Prayagraj)",
    1012: "Ashok Nagar (Prayagraj)",
    1013: "Malakraj (Prayagraj)",
    1014: "Bhadri (Prayagraj)",
    1015: "Jayantipur (Prayagraj)",
    1016: "Bahmalpur (Prayagraj)",
    1017: "Chaka (Prayagraj)",
    1018: "Harwara (Prayagraj)",
    1019: "Andawa (Prayagraj)",
    1020: "Chak Raghunath (Prayagraj)",
    1021: "Myorabad (Prayagraj)",
    1022: "Baswar (Prayagraj)",
    1023: "Sadiyabad (Prayagraj)",
    1024: "Swaraj Nagar (Prayagraj)",
    1025: "Malawa Buzurg (Prayagraj)",
    1026: "Civil Lines First (Prayagraj)",
    1027: "Salori (Prayagraj)",
    1028: "Jhulelal Nagar (Prayagraj)",
    1029: "Mohabbatganj (Prayagraj)",
    1030: "Krishna Nagar (Prayagraj)",
    1031: "Jahangirabad (Prayagraj)",
    1032: "Alenganj (Prayagraj)",
    1033: "Lavayan (Prayagraj)",
    1034: "Shivkuti (Prayagraj)",
    1035: "Jhalwa (Prayagraj)",
    1036: "Madhwapur (Prayagraj)",
    1037: "Shantipuram (Prayagraj)",
    1038: "Baghambari Housing Scheme (Prayagraj)",
    1039: "Malak Harhar (Prayagraj)",
    1040: "Naini Dadri (Prayagraj)",
    1041: "Mamfordganj (Prayagraj)",
    1042: "Ganga Nagar (Prayagraj)",
    1043: "Azad Square (Prayagraj)",
    1044: "Chakiya (Prayagraj)",
    1045: "Chhatnag (Prayagraj)",
    1046: "Pura Padain (Prayagraj)",
    1047: "Arail (Prayagraj)",
    1048: "Alopi Bagh (Prayagraj)",
    1049: "Transport Nagar (Prayagraj)",
    1050: "Katka (Prayagraj)",
    1051: "Mundera (Prayagraj)",
    1052: "Haweliya (Prayagraj)",
    1053: "Chak Niratul (Prayagraj)",
    1054: "Rajruppur (Prayagraj)",
    1055: "Teliarganj (Prayagraj)",
    1056: "Fafamau (Prayagraj)",
    1057: "Kashiraj Nagar (Prayagraj)",
    1058: "Civil Lines Second (Prayagraj)",
    1059: "Neem Sarai (Prayagraj)",
    1060: "Minhajpur Gadhikala (Prayagraj)",
    1061: "Colonelganj (Prayagraj)",
    1062: "Nai Basti (Prayagraj)",
    1063: "Purana Katra (Prayagraj)",
    1064: "Mehandauree (Prayagraj)",
    1065: "Tagore Town (Prayagraj)",
    1066: "Chak Dondi (Prayagraj)",
    1067: "Kazipur (Prayagraj)",
    1068: "Nyay Marg Kshetra (Prayagraj)",
    1069: "Bharadwajpuram (Prayagraj)",
    1070: "Mavaiya (Prayagraj)",
    1071: "Omprakash Sabhasad Nagar (Prayagraj)",
    1072: "Govindpur (Prayagraj)",
    1073: "Prayagraj Ward 73 (Prayagraj)",
    1074: "Prayagraj Ward 74 (Prayagraj)",
    1075: "Prayagraj Ward 75 (Prayagraj)",
    1076: "Prayagraj Ward 76 (Prayagraj)",
    1077: "Prayagraj Ward 77 (Prayagraj)",
    1078: "Prayagraj Ward 78 (Prayagraj)",
    1079: "Prayagraj Ward 79 (Prayagraj)",
    1080: "Prayagraj Ward 80 (Prayagraj)",
    1081: "Prayagraj Ward 81 (Prayagraj)",
    1082: "Prayagraj Ward 82 (Prayagraj)",
    1083: "Prayagraj Ward 83 (Prayagraj)",
    1084: "Prayagraj Ward 84 (Prayagraj)",
    1085: "Prayagraj Ward 85 (Prayagraj)",
    1086: "Prayagraj Ward 86 (Prayagraj)",
    1087: "Prayagraj Ward 87 (Prayagraj)",
    1088: "Prayagraj Ward 88 (Prayagraj)",
    1089: "Prayagraj Ward 89 (Prayagraj)",
    1090: "Prayagraj Ward 90 (Prayagraj)",
    1091: "Prayagraj Ward 91 (Prayagraj)",
    1092: "Prayagraj Ward 92 (Prayagraj)",
    1093: "Prayagraj Ward 93 (Prayagraj)",
    1094: "Prayagraj Ward 94 (Prayagraj)",
    1095: "Prayagraj Ward 95 (Prayagraj)",
    1096: "Prayagraj Ward 96 (Prayagraj)",
    1097: "Prayagraj Ward 97 (Prayagraj)",
    1098: "Prayagraj Ward 98 (Prayagraj)",
    1099: "Prayagraj Ward 99 (Prayagraj)",
    1100: "Prayagraj Ward 100 (Prayagraj)",
};

export const getWardLabel = (id: number) => {
    return WARD_NAMES[id] ? `${id} - ${WARD_NAMES[id]}` : `Ward ${id}`;
};
